### ISSUE TITLE
General ideas for Spine version $Next

### ISSUE THREAD

**Issue by adambiggs** [spine/spine#434]
Given the recent buzz in this repo, I wanted to open up a dialog about ideas for the next big Spine release (v2.0 maybe?). I have more open-source time coming up, and would love to contribute it to Spine!

Here's my wishlist:
- [ ] New API for `Spine.Model` based on [Alex's Gist](https://gist.github.com/maccman/3194153)
- [x] `@find()` to return falsey for missing records instead of throwing exceptions. (discussion in #428)
- [x] ~~AMD support via [UMD](https://github.com/umdjs/umd/blob/master/commonjsStrict.js)~~ (See [comment](https://github.com/spine/spine/issues/434#issuecomment-35011524))
- [x] CoffeeScript source maps (#431)
- [ ] Inline docs via [Literate CoffeeScript](http://coffeescript.org/#literate) (#433)
- [ ] Updated version of spinejs.com
- [ ] Swap out Cake for Grunt/Gulp/other?
- [x] ~~Refactor tests as CoffeeScript, switch to Mocha & Chai, and run CLI tests via [mocha-phantomjs](http://metaskills.net/mocha-phantomjs/)~~ (See [comment](https://github.com/spine/spine/issues/434#issuecomment-107652418))
- [x] Refactor `Spine.Stack` to allow nested stacks & handle multiple routes properly (#373, #398)
- [ ] Storage callbacks (#371)
- [ ] IndexDB storage module (#343)
- [ ] Simple _many to many_ model relationships (I have a module to contribute if there's interest)
- [ ] Ability to include related records in `@toJSON()` output (I've also got code for this)

_Edit_ - More stuff:
- [ ] Return promise objects from any relevant async methods (#328, #429)
- [x] Module for live-binding between models & views

Thoughts?

**Comment by adambiggs** [comment]
Just removed the item about refactoring tests. This would end up being a lot of work without any tangible reward...
